name: Infra Destroy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

env:
  BRANCH_NAME: ${{ github.event.inputs.branch || 'main' }}

permissions:
  id-token: write
  contents: read

jobs:
  infra-destroy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        with:
          terraform_wrapper: false
      - name: Terraform 
        id:   destroy

        run: |
         
         terraform init \
           -backend-config="bucket=tfstate-state-bucket-githubaction" \
           -backend-config="region=eu-west-1" \
           -backend-config="key=main/terraform.tfstate"
         terraform validate
         terraform destroy  --auto-approve
